name: Blog Post

on:
  push:
    branches:
      - main  # 仅在push到main时生效

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Sync posts to server
      run: |
        ls $GITHUB_WORKSPACE
    # - name: Sync posts to server via rsync
    #   uses: appleboy/ssh-action@v1.0.3
    #   with:
    #     host: ${{ secrets.SERVER_HOST }}
    #     username: ${{ secrets.SERVER_USER }}
    #     key: ${{ secrets.SERVER_SSH_KEY }}
    #     port: 22
    #     script: |
    #       ls $GITHUB_WORKSPACE
          