name: Blog Post

on:
  push:
    branches:
      - main  # 仅在push到main时生效

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Post to server
      env:
        server_ssh_key: ${{ secrets.SERVER_SSH_KEY }}
      run: |
        echo "$secrets.SERVER_SSH_KEY" > /tmp/key
        chmod 600 /tmp/key
        cat /tmp/key      
        rm -f /tmp/key

 